language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install flask
  - pip install pep8
# command to run tests, e.g. python setup.py test
script:  
  - pep8 src

